# Generated by Django 5.1.4 on 2024-12-29 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Receta",
            fields=[
                ("id_receta", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=150)),
                ("descripcion", models.TextField()),
                (
                    "tiempo_preparacion",
                    models.PositiveIntegerField(help_text="Tiempo en minutos"),
                ),
                (
                    "dificultad",
                    models.CharField(
                        choices=[
                            ("Fácil", "Fácil"),
                            ("Intermedio", "Intermedio"),
                            ("Difícil", "Difícil"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_estudiante", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Ingrediente",
            fields=[
                ("id_ingrediente", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("cantidad", models.CharField(max_length=50)),
                (
                    "receta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredientes",
                        to="Recetas.receta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                ("id_comentario", models.AutoField(primary_key=True, serialize=False)),
                ("texto", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "receta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="Recetas.receta",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Recetas.usuario",
                    ),
                ),
            ],
        ),
    ]
